# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [13]:
# Import Numpy
import numpy as np
A = np.random.randint(0,11, (2,3))
B = np.random.randint(0,11, (3,5))
C = np.random.randint(0,11, (5,2))
D = np.random.randint(0,11, (3,3))

print(f"A = {A} shape = {A.shape}")
print(f"B = {B} shape = {B.shape}")
print(f"C = {C} shape = {C.shape}")
print(f"D = {D} shape = {D.shape}")

P = np.dot(A,B)
print(P)
Q = np.dot(P,C)
print(Q)
R = np.dot(Q,D)
print(Q)



A = [[8 4 4]
 [9 0 3]] shape = (2, 3)
B = [[ 5  1  3  6  2]
 [ 3  6  4  4 10]
 [ 1  1  1  0  1]] shape = (3, 5)
C = [[ 1  9]
 [10  1]
 [ 1 10]
 [ 0  4]
 [10  7]] shape = (5, 2)
D = [[ 5  2  5]
 [ 6  7 10]
 [ 9  1  7]] shape = (3, 3)
[[56 36 44 64 60]
 [48 12 30 54 21]]
[[1060 1656]
 [ 408 1107]]


ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
# Define the 4 matrices as A,B,C,D

In [ ]:
# Print the 4 matrices

In [ ]:
# Find the Dot Product of matrices


# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [12]:
import numpy as np
def is_compatible(A, B):
  if A.shape[1] == B.shape[0]:
    print(np.dot(A,B))
  else:
    print("Dimensional Error!!")

In [ ]:
# Find Dot product only if the matrices are compatible

# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [6]:
import numpy as np

def up_down(rounds):
    score = 0

    for i in range(rounds):
        player_guess = int(input("Enter a number from 1 to 12"))
        computer_guess = np.random.randint(1, 13)
        print(f"Computer's guess: {computer_guess}")

        if computer_guess < 7:
            if player_guess < 7:
                score += player_guess
            else:
                score -= player_guess
        elif computer_guess == 7:
            if player_guess == 7:
                score += 14
            else:
                score -= player_guess
        else:
            if player_guess > 7:
                score += player_guess
            else:
                score -= player_guess

        print(f"Current score: {score}")

        if score > 30:
            print("You win")
            return
        if score < -30:
            print("You lose.")
            return

    print(f"Final score: {score}")
