# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [1]:
# Import Numpy
import numpy as np

In [2]:
# Define the 4 matrices as A,B,C,D
A = np.random.randint(1,10,(2,3))
B = np.random.randint(1,10,(3,5))
C = np.random.randint(1,10,(5,2))
D = np.random.randint(1,10,(3,3))

In [3]:
# Print the 4 matrices
print(f"A(2X3):\n{A}\n")
print(f"B(3X5):\n{B}\n")
print(f"C(5X2):\n{C}\n")
print(f"D(3X3):\n{D}\n")

A(2X3):
[[6 5 3]
 [6 3 8]]

B(3X5):
[[6 1 6 3 2]
 [4 6 8 6 2]
 [3 4 1 3 5]]

C(5X2):
[[6 6]
 [6 8]
 [6 7]
 [8 7]
 [2 2]]

D(3X3):
[[1 9 3]
 [9 5 5]
 [8 6 6]]



In [4]:
# Find the Dot Product of matrices
AB = np.dot(A,B)
print(f"AB(2x5):\n{AB}\n")
AD = np.dot(A,D)
print(f"AD(2x3):\n{AD}\n")
ABC = np.dot(AB,C)
print(f"ABC(2x2):\n{ABC}\n")

AB(2x5):
[[65 48 79 57 37]
 [72 56 68 60 58]]

AD(2x3):
[[ 75  97  61]
 [ 97 117  81]]

ABC(2x2):
[[1682 1800]
 [1772 1892]]



# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [5]:
def is_compatible(A, B):
  if A.shape[1] == B.shape[0]:
    print(np.dot(A,B))
  else:
    print("Dimension error!!")
  pass

In [6]:
# Find Dot product only if the matrices are compatible
A = np.random.randint(1,10,(2,3))
B = np.random.randint(1,10,(4,5))
print("AxB:")
is_compatible(A, B)


AxB:
Dimension error!!


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [ ]:
import numpy as np

def up_down(rounds):
    score = 0
    for i in range(rounds):
        while True:
            try:
                playerguess = int(input("Enter a number between 1 and 12: "))
                if 1 <= playerguess <= 12:
                    break
                print("Invalid input! Choose a number between 1 and 12.")
            except ValueError:
                print("Invalid input! Enter a valid integer.")

        computerguess = np.random.randint(1, 13)  # Ensuring it includes 12
        print(f"Computer's guess: {computerguess}")

        if computerguess < 7:
            if playerguess < 7:
                score += playerguess
            else:
                score -= playerguess
        elif computerguess == 7:
            if playerguess == 7:
                score += 14
            else:
                score -= playerguess
        else:
            if playerguess > 7:
                score += playerguess
            else:
                score -= playerguess

        print(f"Current score: {score}")

        if score > 30:
            print("You win!")
            return
        elif score < -30:
            print("You lose!")
            return

    print(f"Final score: {score}")

print("Welcome to the game")
up_down(3)


Welcome to the game
