# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [1]:
# Import Numpy
import numpy as np

In [20]:
# Define the 4 matrices as A,B,C,D
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
C = np.array([[1,2], [3,4],[5,6],[7,8],[9,10]])
D = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [24]:
# Print the 4 matrices
print("Matrix A\n",A)
print("Matrix B\n",B)
print("Matrix C\n",C)
print("Matrix D\n",D)

Matrix A
 [[1 2 3]
 [4 5 6]]
Matrix B
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Matrix C
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Matrix D
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Find the Dot Product of matrices
dot_product = np.dot(A, B)
print("\nDot Product of A and B:\n", dot_product)
dot_product = np.dot(B, C)
print("\nDot Product of B and C:\n", dot_product)
dot_product = np.dot(C, A)
print("\nDot Product of C and A:\n", dot_product)
dot_product = np.dot(D, D)
print("\nDot Product of D with D:\n", dot_product)


Dot Product of A and B:
 [[ 46  52  58  64  70]
 [100 115 130 145 160]]

Dot Product of B and C:
 [[ 95 110]
 [220 260]
 [345 410]]

Dot Product of C and A:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]
 [39 54 69]
 [49 68 87]]

Dot Product of D with D:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [29]:
def is_compatible(A, B):
  numcol = len(A[0])
  numrow = len(B)
  if numcol != numrow:
    return False
  else:
    return True

In [31]:
# Find Dot product only if the matrices are compatible
def get_dot(A,B):
    if(is_compatible(A,B)):
        print(np.dot(A,B))
    else:
        print("Dimension Error")
    print()

get_dot(A,B)
get_dot(B,C)
get_dot(D, A)

[[ 46  52  58  64  70]
 [100 115 130 145 160]]

[[ 95 110]
 [220 260]
 [345 410]]

Dimension Error



# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [ ]:
def up_down(rounds):
  user_score = 0
  while int(rounds) > 0 :
    
    user_guess = int(input("Enter a number to guess: "))
    guess = int((np.random.rand()*12)+1)

    print(f'You guessed {user_guess} and computer guessed {guess}')
    if (guess < 7):
      if user_guess < 7:
        user_score = user_score + user_guess
      else:
        user_score = user_score - user_guess


    if (guess == 7):
      if user_guess == 7:
        user_score = user_score + 14
      else:
        user_score = user_score - user_guess


    if(guess > 7):
      if user_guess > 7:
        user_score = user_score + user_guess
      else:
        user_score = user_score - user_guess
    
    if user_score > 30:
      print(f"You win! Score: {user_score}")
    elif user_score < -30:
      print("You lose....")

    rounds = rounds - 1
  
  print(f"Final score: {user_score}")
  
  
up_down(int(input("Welcome to Guessing Game! Enter the number of rounds: ")))


You guessed 11 and computer guessed 10
You guessed 4 and computer guessed 10
You guessed 8 and computer guessed 11
You guessed 1 and computer guessed 7
You guessed 9 and computer guessed 10
You guessed 3 and computer guessed 2
You guessed 6 and computer guessed 9
You guessed 7 and computer guessed 9
Final score: 13
